# Generated by Django 5.0.1 on 2024-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(verbose_name='Գլխավոր էջ՝ քոլեջի մասին')),
                ('address', models.CharField(max_length=100, verbose_name='Հասցե')),
            ],
            options={
                'verbose_name': 'Գլխավոր էջի տվյալներ',
                'verbose_name_plural': 'Գլխավոր էջի տվյալներ',
            },
        ),
    ]
