# Generated by Django 5.0.1 on 2024-02-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_professions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Բաժնի մասին տեղեկություններ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profdetail', to='main.professions')),
            ],
            options={
                'verbose_name': 'մանրամասն տեղեկություններ',
                'verbose_name_plural': 'մանրամասն տեղեկություններ',
            },
        ),
    ]
