# Generated by Django 5.0.1 on 2024-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Անուն ազգանուն')),
                ('prof', models.CharField(max_length=50, verbose_name='Զբաղեցրած պաշտոն')),
                ('img', models.ImageField(upload_to='Staffs', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Աշխատակազմ',
                'verbose_name_plural': 'Աշխատակազմ',
            },
        ),
    ]
