# Generated by Django 5.0.1 on 2024-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Հարցը')),
                ('answer', models.TextField(verbose_name='Պատասխան')),
            ],
            options={
                'verbose_name': 'Հարց և պատասխան',
                'verbose_name_plural': 'Հարց և պատասխան',
            },
        ),
    ]
