# Generated by Django 5.0.1 on 2024-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dimord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimord',
            name='img',
            field=models.ImageField(null=True, upload_to='dimord', verbose_name='Նկար'),
        ),
    ]
