# Generated by Django 5.0.1 on 2024-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_myvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Անուն')),
                ('subject', models.CharField(max_length=50, verbose_name='Ենթատեքստ')),
                ('message', models.TextField(verbose_name='Հաղորդագրություն')),
            ],
            options={
                'verbose_name': 'Հաղորդագրություններ',
                'verbose_name_plural': 'Հաղորդագրություններ',
            },
        ),
    ]
