# Generated by Django 5.0.1 on 2024-02-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Մեկնաբանություն')),
                ('nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namee', to='main.staffs')),
            ],
            options={
                'verbose_name': 'Աշխատակազմի կարծիքներ',
                'verbose_name_plural': 'Աշխատակազմի կարծիքներ',
            },
        ),
    ]
