# Generated by Django 5.0.1 on 2024-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_substuffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Գլխավորի տեքստ')),
            ],
            options={
                'verbose_name': 'Գլխավորի տեքստ',
                'verbose_name_plural': 'Գլխավորի տեքստ',
            },
        ),
    ]
