# Generated by Django 5.0.1 on 2024-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_titletext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titletext',
            options={'verbose_name': 'Գլխավորի տեքստ և նկար', 'verbose_name_plural': 'Գլխավորի տեքստ և նկար'},
        ),
        migrations.AddField(
            model_name='titletext',
            name='img',
            field=models.ImageField(null=True, upload_to='main_imagers', verbose_name='Գլխավոր նկար'),
        ),
    ]
