# Generated by Django 5.0.1 on 2024-02-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0002_enprofessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enprofessions',
            options={'verbose_name': 'Professions', 'verbose_name_plural': 'Professions'},
        ),
    ]
