# Generated by Django 5.0.1 on 2024-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0003_alter_enprofessions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enprofessions',
            name='img',
            field=models.ImageField(upload_to='Professions imagers', verbose_name='Imagers'),
        ),
        migrations.AlterField(
            model_name='enprofessions',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of specialty'),
        ),
    ]
