# Generated by Django 5.0.1 on 2024-02-06 19:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0005_enprofdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number (+374)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'contacts',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='EnQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
            ],
            options={
                'verbose_name': 'question and answer',
                'verbose_name_plural': 'question and answer',
            },
        ),
        migrations.CreateModel(
            name='EnStaffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Surname')),
                ('prof', models.CharField(max_length=50, verbose_name='The position held')),
                ('img', models.ImageField(upload_to='Staffs', verbose_name='Imagers')),
            ],
            options={
                'verbose_name': 'Stuff',
                'verbose_name_plural': 'Stuff',
            },
        ),
    ]
