# Generated by Django 5.0.1 on 2024-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0007_endimord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endimord',
            options={'verbose_name': 'applicant', 'verbose_name_plural': 'applicant'},
        ),
        migrations.AlterField(
            model_name='endimord',
            name='img',
            field=models.ImageField(null=True, upload_to='dimord', verbose_name='imgers'),
        ),
        migrations.AlterField(
            model_name='endimord',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name='Distinguished line at the beginning of the text '),
        ),
        migrations.AlterField(
            model_name='endimord',
            name='text',
            field=models.TextField(verbose_name='The rest of the text'),
        ),
        migrations.AlterField(
            model_name='endimord',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
