# Generated by Django 5.0.1 on 2024-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0010_alter_enpdfiles_options_alter_enpdfiles_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnMyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video', verbose_name='Տեսանյութ')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
