# Generated by Django 5.0.1 on 2024-03-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0011_enmyvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Անուն')),
                ('subject', models.CharField(max_length=50, verbose_name='Ենթատեքստ')),
                ('message', models.TextField(verbose_name='Հաղորդագրություն')),
            ],
            options={
                'verbose_name': 'Հաղորդագրություններ',
                'verbose_name_plural': 'Հաղորդագրություններ',
            },
        ),
        migrations.CreateModel(
            name='EnSubStuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='comment')),
                ('nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namee', to='English.enstaffs')),
            ],
            options={
                'verbose_name': 'Staff opinion',
                'verbose_name_plural': 'Staff opinions',
            },
        ),
    ]
