# Generated by Django 5.0.1 on 2024-03-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English', '0012_encontact_ensubstuffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnTitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Main text')),
            ],
            options={
                'verbose_name': 'Main text',
                'verbose_name_plural': 'Main text',
            },
        ),
    ]
